export enum ComparisonFunctionEnum {
  Eq = 'eq',
  Ne = 'ne',
  Gt = 'gt',
  Lt = 'lt',
  Gte = 'gte',
  Lte = 'lte',
  And = 'and',
  Nand = 'nand',
  Or = 'or',
  Nor = 'nor',
  Xor = 'xor',
  Xnor = 'xnor',
  In = 'in',
  Nin = 'nin',
  All = 'all',
  Not = 'not',
}
